language: node_js
node_js:
- '0.11'
- '0.12'
- node
- iojs
sudo: false
deploy:
  provider: npm
  email: andrew@balmos.org
  api_key:
    secure: dwXl/qiXcl7IiQNUn+BchAYtGFElAnHfpJAvRo6h5je/mqC6SIHFeavqSgEhWOPPa8RxnIr5mlk0zSZpEVaNPcNlKX0kCpDcVQpHmsO+c4jU5PpOP8CYldJENAKH4VuR0MlYHEPOL7eP+egRmB9Xjt1NnZKAhEa3YzDLsyDs4ELbWekRiwUjgWDsoYtaeUO9l2ji+KDIMbVi2dn5ywHz1muSNfKg7wslQUZYaQtrXHXrDn/TKItqlvzhx6d9mY5OWcb/dD0gxv5Z2ShEsw0oJ7O4G5j9sD7fejNH6D1fIr33l8E6iLKw3w8sLESZphGa4jAPRl02KPTr18ZM2NuymxHKHm/AnlbRAxXL0YUaFLGgbbLrc0+xxec3/JburdANY9l8GNzAn6YvKPcgtvJt9DkfEE4ZKMDPUBYmaEcqNqPGBVhnRUzI9mybJsN2vjiUm2eXgax+trWMSaD3yZUWC5SymzLqn3L/49t9nyjwHZDDyMhgIND7qqSUP7R/JdojBuqMXv0nWv5ZYps9t5WRGknuCwqvTJNHtQx4WtNXv0cPWGm25MdEqNKbcJ6FpPdqBisJmmrJKRNnJDJ+uT2cdzBgxmABtBdvjGrQwQZTI6kr47XGRvE2x0r6t3mHxC0iFY0Q7hjMOPsPoqrDMauCwMm9mOdQSNb5WzltFT4DBUc=
  on:
    tags: true
    repo: OADA/oada-formats
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run style
- npm run cover
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
