language: node_js
node_js:
- '0.11'
- '0.12'
- node
- iojs
sudo: false
deploy:
  provider: npm
  email: info@openag.io
  api_key:
    secure: IKhSGwjklxezAAYeILBNgx8KQzEqdru8HC1w+Zl2IWGAYw8ENU6BigUZhR87zA8jy2SVPmLb+7IvHGjl8QR5Y3kqHzssRJmFDmOU+b1T7F+NrwPDsuiXegemBMsupMx0FX5/VdUOT0G7LovysQV0t+mAG/1oyZRIrQvqMVmpRm4hrVMxoSmQS/9F7Efp/f34jf/aSucw6dnCWC+8M4X7bOBLGHEFfg6BgpWsLVAM5z6QKVRtaBCrvzB9DGfeS/+jKrmT4Hb1+DNwGlORI1P5nReEog1mpf8SlUNSXIAGzjsu0poWfBisBL8Ljd/xdcKUCuUdr7Y8xcszaD6sJMyyAQ+VwOaazryRowUlDmn6l4jvT6Bc8p/KMphYK5rd9BMWpF3NKO1DXb+q19NXnf89DpNtCuRX+7oCoXUn8KkkwmeJ8/fB946ERBpuo2RDAHbC5BrSLO5YgydQaswETkyn5pPE7H+bAJkHduimKBtDy4AibHq1Aunp8pQOfoZD3Sp7Txz9q4PVWFn7ut9IF4bbFuchVTpunjtJUSv3thBY7EbajxrMe7ISDQZVX9IYjBbcEacCFZJOQArZ1o7YNLbJwl5Z6WFqI8BIxOkffbVfUoC41CnEw4PYA2qojotRbPv4YEZskDeiYLiaRP4BQ0b9BdHxLPAtJ5TISNlIhomrNIM=
  on:
    node: node
    tags: true
    repo: OADA/oada-formats
before_install:
- npm install -g coveralls
script:
- npm run lint
- npm run style
- npm run cover
after_success:
- cat ./coverage/lcov.info | coveralls --verbose
